alias aelog='tail -f /var/log/httpd/error_log.`date +"%Y-%m-%d"`'
alias alog='cd /var/log/httpd/; ls -rt | grep access | tail -1 | xargs tail -f'
alias h='history'
alias ll='ls -l'
alias al='ls -al'
alias aconf='sudo nano /etc/httpd/conf/httpd.conf'
alias web='cd /var/www/html'
